#include "commcontrol.h"

const LPCWSTR _WC_BUTTON = WC_BUTTON;
const LPCWSTR _WC_EDIT = WC_EDIT;
const LPCWSTR _WC_TREEVIEW = WC_TREEVIEW;

BOOL InitializeCommonControls() {
    INITCOMMONCONTROLSEX arg={0};
    arg.dwSize = sizeof(arg);
    arg.dwICC =  ICC_LISTVIEW_CLASSES | ICC_TREEVIEW_CLASSES | ICC_BAR_CLASSES | ICC_TAB_CLASSES | ICC_UPDOWN_CLASS | ICC_PROGRESS_CLASS | ICC_HOTKEY_CLASS | ICC_ANIMATE_CLASS |
     ICC_WIN95_CLASSES | ICC_DATE_CLASSES | ICC_USEREX_CLASSES | ICC_COOL_CLASSES | ICC_INTERNET_CLASSES | ICC_PAGESCROLLER_CLASS | ICC_NATIVEFNTCTL_CLASS /*| ICC_STANDARD_CLASSES | ICC_LINK_CLASS*/;
    return InitCommonControlsEx(&arg);
}

